### ISSUE TITLE
pouziatelske rozhranie

### ISSUE THREAD

**Issue by dobsovicova** [TIS2017/SportovyKlub#11]
issue na C cast pe Navrh.

**Comment by dobsovicova** [comment]
posli prosim Mati fotky p. Baloghovi, aby sme vedeli, ci to tak moze byt. Dakujem. #11

**Comment by duricova72** [comment]
Ok, pošlem.

**Comment by gabikaSlani** [comment]
Už máte potvrdenie od p. Balogha?

**Comment by duricova72** [comment]
Ešte som mu to neposlala, lebo boli sviatky. Pošlem dneska. :)

**Comment by duricova72** [comment]
Poslané. Čakáme na odpoveď. 
Pripájam dokument, ktorý som poslala na zhodnotenie zadávateľom.
[navrh_dizajnu.pdf](https://github.com/TIS2017/SportovyKlub/files/1443971/navrh_dizajnu.pdf)

**Comment by duricova72** [comment]
Prišla už odpoveď. Izi, kukni to, potom sa pustíme do opravy. :)
Mail od zadávateľa:

zopar pripomienok skusim:

str. 1: bud namiesto tlacitiek nejake male ikonky, alebo text potom len A (aktivovat), Cc (Kopirovat) a X (vymazat) - takto to zabera zbytocne vela miesta a admin uz bude vediet co to znamena.

str. 2: mozno ze ked vytvaram novy zaznam, tak uz tam nemusi byt cely zoznam treningov ci nie?

str. 4: kategorie su na tomto obrazku v pohode, ale ked ich bude vela, mozno by mohli byt v dvoch stlpcoch, co myslite?


str. 6 - export je super, ale volbu konfiguracie by som mozno nechal v admin rozhrani a tu len tlacidlo na vygenerovanie.
Lebo ten export si nastavim raz a bude to navzdy, mozno ked o 3 roky niekto zmeni specifikaciu, tak tam pridam alebo zmenim
poradie, ale inak nebudeme menit format. Preto som vravel, ze to by mi nevadilo, keby bolo aj priamo v nejakom subore na serveri,
na to nemusime generovat formular. Mozeme, ale nemusime.
Teraz ked vidim aky dlhy je ten stlpec s neprihlasenymi, tak rozmyslam, ci by nepomohol nejaky filter ale mozno aj netreba, ak bude
dobre fungovat to obmedzovanie podla cookies.
Tu nerozumiem celkom co znamena upravili sme dvojity scroller.


str. 7 Archiv pretekov takto asi nema velky zmysel , mozno by tam tiez mohli byt tie tri tlacidla A(ctivate), X(delete), C(copy) pri kazdom z nich.

str. 8 tabulka so zoznamom ludi - asi by tam mohlo byt celkom vpravo okrem Vymaz aj tlacidlo Uprav a Update alebo nieco podobne aby sa dali udaje editovat.

str. 11 na tejto tabulke mi chyba dole tlacidlo export a neviem naco su tu checkboxy, asi nanic.

Dakujem.

**Comment by dobsovicova** [comment]
Okej. No... Tak to cez týždeň spracujeme.

**Comment by duricova72** [comment]
![zadavatel_oficialne_vyjadrenie_navrh](https://user-images.githubusercontent.com/26030914/32690724-56b6763a-c6fb-11e7-8ec7-dff67df70a98.PNG)

**Comment by duricova72** [comment]
Už máme vyjadrenie od zadávateľa a odsúhlasil našu úpravu po zapracovaní jeho pripomienok.

**Comment by pavelpetrovic** [comment]
dakujem, budem sa teda prilezitostne tesit na cely dokument navrh. kedze nemame stretnutie v pondelok, skusim dat spatnu vazbu mailom, aby ste ju mali skor ako o tyzden.
