### ISSUE TITLE
vytvorenie dátového modelu

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#15]
Livka ked exportuješ tú poslednu verziu dátového modelu nahraj ju prosím sem

**Comment by lyvija** [comment]
![dat_model](https://user-images.githubusercontent.com/26010477/32414315-2c889680-c224-11e7-8026-5b18d94b4600.gif)

**Comment by lyvija** [comment]
Pozrite sa na to prosím

**Comment by gabikaSlani** [comment]
pridali sme do databazy tu tabulku KMEN_CLENOVIA inak zostava vsetko ako bolo povodne. Primarny kluc v tabulke KATEGORIE je NAZOV typu TEXT...nie je to chyba ale v predchádzajúcej verzii to tak bolo

**Comment by dobsovicova** [comment]
Vyzerá to byť dobre ;)

**Comment by lyvija** [comment]
![dat_model](https://user-images.githubusercontent.com/26010477/32614769-43fdb32a-c56e-11e7-9576-bec18cb35f2d.gif)

**Comment by lyvija** [comment]
Kľúče opravené, aj ten text som dajak zjednotila. Pozrite prosím, či to sedí.

**Comment by gabikaSlani** [comment]
noo hned to je lepsie :) super

**Comment by duricova72** [comment]
áno, je to lepšie, super. :)

**Comment by pavelpetrovic** [comment]
môžete, prosím, nejakým farebným zvýrazňovačom označiť všetko, čo sa nejak zmenilo oproti predchádzajúcej verzii?

**Comment by lyvija** [comment]
![dat_model](https://user-images.githubusercontent.com/26010477/32701127-3933be9e-c7d0-11e7-9710-e2e03112909b.gif)

**Comment by lyvija** [comment]
Zmeny zvýraznené + doplnená tabuľka Exporty. Snáď dobre.

**Comment by lyvija** [comment]
![dat_model](https://user-images.githubusercontent.com/26010477/32794724-ed651800-c969-11e7-92b9-e31ed0b29347.gif)

**Comment by lyvija** [comment]
Opravila som zvýraznenie a exporty som rozmýšľala, že by sme mohli spraviť inak (jednoduchšie), preto iná tabuľka - vysvetlenie rozpíšem do nášho dokumentu.
