### ISSUE TITLE
UML diagramy

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#16]
Takže vybrali sme si sekvenčný a use-case. Pracujem na nich. O chvílku ich sem nahrám, aby ste skontrolovali, či súhlasíte :)

**Comment by gabikaSlani** [comment]
![sekvencny_export](https://user-images.githubusercontent.com/25964352/32414393-c230436c-c225-11e7-86d9-4b2e709c11c4.png)
![sekvencny_kmen](https://user-images.githubusercontent.com/25964352/32414394-c250e6bc-c225-11e7-91b6-8127b6904fbb.png)

**Comment by gabikaSlani** [comment]
Ten prvý je sekvenčný čo sa týka exportu prihlásených používateľov do súboru. Ten druhý je sekvenčný vytvorenia nového kmeňového člena

**Comment by gabikaSlani** [comment]
USE-CASE diagram
![use-case](https://user-images.githubusercontent.com/25964352/32414405-08af43ec-c226-11e7-926a-7a4324654b31.png)

**Comment by duricova72** [comment]
Podľa mňa je to super. Výstižné, podľa podmienok zadávateľa. :)

**Comment by dobsovicova** [comment]
Paráda dievčatá ;) Za mňa môže byť

**Comment by pavelpetrovic** [comment]
porozprávame sa o tom, dúfam, zajtra na stretnutí, zatiaľ vďaka.

**Comment by gabikaSlani** [comment]
USE-CASE opravený. Skontrolujte hlavne to, že kde robíme zmeny, či som niečo nezabudla. Ď
![use case diagram](https://user-images.githubusercontent.com/25964352/32550105-313b0c20-c48c-11e7-8d53-00a8961e7e6d.png)

**Comment by gabikaSlani** [comment]
Sekvenčné Diagramy:
![sequence diagram export](https://user-images.githubusercontent.com/25964352/32550191-79a47582-c48c-11e7-94f3-cb02d3142262.png)
![sequence diagram kmen clen](https://user-images.githubusercontent.com/25964352/32550196-7db6530c-c48c-11e7-9904-e5c273a6a436.png)

**Comment by duricova72** [comment]
podľa mňa je to fajn. :)

**Comment by pavelpetrovic** [comment]
mám problém so šípkou "zapíše zoznam do súboru" a "link na vytvorený súbor".
neviem, čo tým chcete povedať, ale nahradil by som to jedinou šípkou s popisom napr.
"stránka so zoznamom používateľov" a následne šípka k používateľovi
"zobrazený zoznam".

potom v druhom diagrame nerozumiem, preco ten optional blok nasleduje za tou prvou castou a ako s nou suvisi a preco vlastne je optional.

**Comment by pavelpetrovic** [comment]
v use-case je ten velky oval podla mna zbytocny a iba komplikuje layout, ale asi na tom nezalezi.

**Comment by gabikaSlani** [comment]
use-case bez ovalu
![use case diagram](https://user-images.githubusercontent.com/25964352/32602401-44e51080-c546-11e7-9d18-615a605737c1.png)

**Comment by gabikaSlani** [comment]
čo sa týka toho exportu, chceme tým povedať že zoznam používateľov vytiahnutý z databázy sa zapíše do súboru uloženom na serveri a následne používateľa presmeruje na tento súbor...pôvodne som tam mala "presmeruje používateľa na vytvorený súbor" ale na stretnutí ste navrhli že by tam bol lepší popis "link na súbor"

**Comment by gabikaSlani** [comment]
pri tom druhom sekvenčnom: optional blok súvisí s prvou časťou tak, že pokial nie je používateľ zaregistrovaný(teda prihlásený na nejaký pretek) nemôže byť zvolený za kmeňového člena. Optional je preto lebo administrátor môže ale nemusí zvoliť používateľa za kmeňového člena. Aby mohol používateľa zvoliť za kmeňového člena, musí sa prihlásiť a dostať sa do profilu daného používateľa

**Comment by pavelpetrovic** [comment]
k prvému: vyrobili ste tam guláš. server keď zapisuje zoznam do súboru, tak to určite nie je správa, ktorú by server posielal webovej stránke. ten link (druhá z tých dvoch správ) by sa dal pochopiť, ale potom je tam ešte aj tak guláš v tom, čo je webová stránka - či je to to, čo sa zobrazilo v browseri a s čím komunikuje používateľ (ako sa zdá podľa komunikácie v hornej časti), alebo či je to len súbor, ktorý je uložený, resp. generovaný na servri (tam by malo logiku zapísať do neho linku na ten exportovaný súbor). zišlo by sa dať to trochu do poriadku. 

k druhému: ta súvislosť mi pripadá ako nepriama...
presnejšie, tie dve časti tohto scenára sú nezávislé, zúčastňujú sa ich iné používateľské roly a typicky sa dejú v inom čase, preto ich umiestnenie do jedného diagramu nie je primerané.

**Comment by gabikaSlani** [comment]
a čo keby to bolo takto? 
![sequence diagram export - page 1](https://user-images.githubusercontent.com/25964352/32606867-2fc1f784-c557-11e7-8175-f42ee3783755.png)

k druhému: pomohlo by keby som tú prvú časť odstránila a OPT posunula od "zvolí ako kmeňového člena"?

**Comment by gabikaSlani** [comment]
alebo vlastne OPT tam tým pádom ani byť nemusí

**Comment by pavelpetrovic** [comment]
ešte k tomu use-case: tým, že išiel veľký ovál preč, tak teraz už nemusia byť všetky malé ovály nad sebou, ale môžete lepšie využiť miesto a rozmiestniť ich aj vedľa seba, aby to celkovo zabralo menej miesta a okrem toho možno budete môcť využiť aj vzťahy <<extend>> a <<include>> (https://www.uml-diagrams.org/examples/use-case-example-airport.png)

v tom "keby to bolo takto?" si nie som istý, prečo je vlastne kontext na webovej stránke aj na webovom servri prerušený, keď sa vlastne tá správa stále spracováva. kým sa nejaká správa spracováva, tak má byť kontext súvislý. tá nová verzia je inak asi lepšia, aj keď stále nie je veľmi zrozumiteľná.

k OPT: ano, opt tam potom byť nemusí, ale tú prvú časť toho diagramu hádam netreba mazať, len snáď to rozdeliť na dva samostatné.

**Comment by gabikaSlani** [comment]
USE-CASE
![use case diagram](https://user-images.githubusercontent.com/25964352/32698312-bfc794e4-c7a3-11e7-8908-30a28a1d1bf5.png)

SEKVENČNÝ - export
![sequence diagram - export - new](https://user-images.githubusercontent.com/25964352/32698314-ce42d6be-c7a3-11e7-9713-d6df42ee71db.png)

SEKVENČNÝ - prihlásenie na pretek
![system sequence diagram - prihlasenie - new](https://user-images.githubusercontent.com/25964352/32698318-ee8bad06-c7a3-11e7-9b25-25df3857442e.png)

SEKVENČNÝ - vloženie kmeňového člena
![system sequence diagram - kmen_clen - new](https://user-images.githubusercontent.com/25964352/32698322-0403b2e6-c7a4-11e7-8634-7263b895e373.png)

**Comment by pavelpetrovic** [comment]
ďakujem, je to pekné. ak by som si mohol vybrať, tak by sa bublinky v use-case nedotýkali, ale nemusíte to kvôli tomu meniť. ak webovú stránku premenujete na webový prehliadač, tak si nebudem lámať hlavu nad tým, čo znamená, keď webový server posiela obsah súboru webovej stránke, ale je to ok tak či tak. budem sa tešiť na celkový dokument s návrhom.
