### ISSUE TITLE
navrh dokument

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#17]
Keby boli nejaké otázky pri tvorbe dokumentu sem s nimi :)

**Comment by gabikaSlani** [comment]
Pridala som už naformátovaný návrh do vetvy gabikaNavrh. Pozrite sa na to prosím.

**Comment by lyvija** [comment]
Nahrala som upravený návrh - doplnený úvod k dokumentu, dokončená posledná veta.

**Comment by gabikaSlani** [comment]
Myslím že môžeme uzavrieť issue a aj vymazať vetvu gabikaNavrh.
