### ISSUE TITLE
testovacie scenáre

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#18]

**Comment by gabikaSlani** [comment]
Vytvorila som novú vetvu testScenare. Je tam už nahratý dokument. Prosím skontrolovať :)

**Comment by gabikaSlani** [comment]
Spravila som tam tie posledné úpravy. Môžete mi to mergnúť a vetvu môžeme vymazať a uzavrieť issue.

**Comment by duricova72** [comment]
ok, zatváram.
