### ISSUE TITLE
Specifikacia poziadaviek

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#2]

**Comment by pavelpetrovic** [comment]
v zapisnici som si precital:
"komunikácia cez skupinu na sociálnej sieti ohľadom dokumentácie"
je to OK, ale uprednostnoval by som, aby tazisko komunikacie islo tu cez issues. 
najma veci typu: 
 - treba urobit este xy...
 - urobila som cdefg...
 - nahravam pracovnu verziu, clen timu Z pozri sa na to a uprav...
a podobne.
dakujem
Pavel

**Comment by pavelpetrovic** [comment]
dobry den, tu su moje pripomienky k prvej verzii katalogu poziadaviek. prosim spracovat, nahrat novu verziu s notifikaciou, a pred poslanim zadavatelovi pockat na moje dalsie pripadne pripomienky, alebo suhlas. dakujem. 

- odkaz na technicku dokumentaciu z predchadzajucej aplikacie
- ak uvadzate cookies v tomto dokumente, tak, prosim, presne napiste, ako sa tie cookies aktualne vyuzivaju - co sa uklada, na co sa to pouzije a ako dlho to tam zostane, ake su s tym presne problemy a ci sa to cele neda riesit nejak inak, lepsie, alebo opravit. nie je to z dokumentu jednoznacne. dakujem
- mozno to zadavatel nechce, ale neponukli by ste mu moznost pridat k treningu aj obrazky, resp. subory? nie je to tazke naprogramovat (jeden uploadovaci formular a jedna tabulka, ktora si bude pamatat zoznam obrazkov pre jednotlive treningy)
- vseobecne obmedzenia obsahuju basnicke zamyslenie nad touto dichotomiou bez vysledneho zaveru ako teda
- vzhladom na to, ze "vstupne podmienky", "vystupne podmienky" a "opakovatelnost" nepouzivate (az na jednu vynimku, ktora sa da napisat inak), tie tabulky nemaju zmysel a len zhorsuju citatelnost dokumentu, preto ich, prosim vyhodte a nechajte tam iba normalne ocislovane poziadavky formulovane ako vety, dakujem.

- konkretne:

3.1.1 - co je sablona? ktore kategorie sa predvyplnia?
        preco je 3.1.1 pod 3.1 ? co to ma s cookies?
        administrator sa tiez prihlasuje z roznych browserov, takze
        hadam nebudu tie predvyplnene polia ulozene v cookies!?

3.1.2 a 3.1.3 - to sa tyka aj toho, co je uvedene vyssie. z dokumentu nie je jasne, co sa do cookies zapamatava, takze sa tejto poziadavke neda rozumiet. navyse tato poziadavka hovori, ze sa nieco rusi a nie je jasne, ci sa to niecim inym nahradza... a z hladiska pouzivatela teda vobec nie je jasne, ci pouzivatel o nejaku funkcionalitu pride, alebo nie...

v principe su cookies technicky detail, ktory by sa v tomto dokumente ani nemal objavit, ale ak ste o tom so zadavatelom hovorili, tak potom ano, len to treba lepsie vysvetlit

3.2.1. prosim uviest konkretne o ake tlacidla ide

3.2.2. prosim konkretnejsie. co nie je teraz user-friendly a co znamena, ze to bude viac user-friendly.

3.2.4. nie je jasne, co je kategoria treningu a ako sa tie kategorie vytvaraju, edituju, mazu...!!? (slovnik pojmov? dalsie poziadavky?)
3.2.8. znie tak, ako keby tam uz nejake kategorie boli, ale 3.2.4. vyzera, ze nie, nedava to spolu logiku
3.2.5. nie je jednoznacne, co je poznamka treningu? jednoriadkove pole? viacriadkova poznamka? akej maximalnej dlzky?
3.2.6. vacsie je uplne nejasna informacia. treba napisat presne.
3.2.7., 3.2.8. akej stranky? na tej stranke je este nieco ine zobrazene? preco? co?
3.2.9. co znamena kopirovat? v style CTRL-C (copy) a CTRL-V (paste) alebo vytvorit kopiu? cim sa potom kopia bude lisit? treba uviest presne!
3.2.10. vobec nerozumiem. precitali ste si po sebe, co ste napisali? ake klikunie kam, kedy sa co zobrazi? co znamena "tabuľke prihlásení používatelia". kde sa "klika na trening"?
        ak v poziadavkach opisujete klikanie a tabulky, tak najlepsie by bolo do dokumentu zaradit odfotene vsetky obrazovky z aktualneho pouzivatelskeho rozhrania, pomenovat ich a v tomto dokumente sa na ne konkretne odkazovat. aj zadavatelovi aj vam a aj ostatnym stakeholderom bude potom presne jasne o co ide a ako to myslite.
3.2.11. podobne
3.2.12. ktoreho pouzivatela a ktora pouzivatelska rola to moze urobit? (to sa tyka vsetkych bodov)
3.3.1. v 2.2. sa pise, ze "je možné usporiadanie podľa dátumu." a tu sa pise, ze je to tak vzdy => nekonzistentnost
3.3.2. co je to za priecinok? co v nom je? nebude to tam pribudat znova? netreba to mazat automaticky casto?
3.4.1. nerozumiem
3.4.2. co je archiv treningov? komu kde ako a co presne tam?
3.4.3. co je deadline na prihlasovanie? kto kde ako? ani admin?
3.5.1. co je export, v akom formate je? co sa exportuje? akej tabulky?
3.6.1. co su zakladne informacie? presne
3.6.2. co su podrobnejsie informacie o clenoch?
nechceli by ste tam pridat moznost nahrat si fotku/avatar? clenovia by sa lahsie spoznavali a nie je to tazke spravit...
3.6.3. nerozumiem, co znamena usporiadat podla stlpcov

**Comment by duricova72** [comment]
Ďakujeme za pripomienky. Hneď ako ich zapracujeme do katalógu, tak ich pošleme.

**Comment by pavelpetrovic** [comment]
ďakujem pekne za rýchle úpravy. tu sú ešte drobnosti, ktoré prosím zvážte upraviť:

- linka na pôvodnú tech. dokumentáciu je z dva roky starého projektu, minulý rok sa pracovalo v tomto repozitári: https://github.com/TIS2016/Sportovy-klub

- tým "súborom cookies" z dokumentu stále nerozumiem. sú to cookies browsra? čiže ak sa ten človek prihlási z iného browsra, tak nemá nič? a to je dobre? alebo sú to iné cookies?

- 3.1.2. asi som ťažko chápajúci, ale naozaj nerozumiem.
  pri ďalšom prihlasovaní na tréning prihlási automaticky všetkých z cookies bez toho, aby to mohol zmeniť??? (niekoho pridať alebo ubrať?) ak môže pridať/ubrať, tak ako a toto sa zasa do tých cookies uloží?
 ak podľa navrhovanej zmeny v zozname neprihlásených budú len tí z cookies, tak nemá šancu tam niekoho iného z neprihlásených pridať??
trochu ma to zmiatlo :-)

- problém s prihlasovaním by sa dal podľa mňa elegantne vyriešiť tak, že by sa dalo prihlásiť jedným tlačidlom pomocou účtu na Google... neuvažovali ste nad tým? nie je to ťažké spraviť... to by ste určite zvládli. :)

- drobnosť: po slovensky je tlačidlo, nie tlačítko :)  (Andrej Blaho by sa potešil)

- ešte len pre istotu k tým obrázkom, ktoré sú z akuálnej verzie, dopísali by ste do popisku obrázku, že ide o aktuálny stav, aby to čitateľ náhodou zle nepochopil?

- veľmi sa teším, že sa tam objavila fotografia v 3.6.2. ale trochu mi nie je jasne, kde sa vzala, kto ju tam ako nahral, či ju môže zmeniť a čo sa urobí, keď fotografiu nenahral.

- v tých textových poliach, keď nechcete povedať presnú novú dĺžku, môžete aspoň sľúbiť, koľko aspoň znakov sa tam už vôjde? a nenapísali ste, či je jednoriadkový, alebo môže byť aj viacriadkový

- 3.2.8 sa týka iba admina, áno? je možné nejakú kategóriu zmeniť/vymazať, alebo iba pridávať? píšete o tom v 2.2 ale v časti 3 to nevidím => nekonzistencia/neúpnosť

 - keďže upravujete existujúcici systém, uveďte prosím niekde zoznam všetkých stránok s jednoriadkovým popisom ku každej, ktoré sú v súčasnom systéme a rozdeľte to na viditeľné adminom a používateľom. lebo takto sa v dokumente odkazujete na niečo, čo tam nie je vysvetlené

- ak admin môže prihlasovať aj po deadline, bolo by dobre to zdôrazniť, lebo implementácia, kde by to nebolo možné nebude v konflikte s takýmto katalógom požiadaviek, čiže nie je to jednoznačné...

Keď tieto úpravy nejak vhodne zapracujete, pošlite, prosím, Katalóg požiadaviek zadávateľovi s tým, že nech vám pošle svoje pripomienky, prípadne súhlas. 

dobrá práca, ďakujem!
