### ISSUE TITLE
rozdelenie uloh

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#21]

**Comment by gabikaSlani** [comment]
[rozdelenie práce.docx](https://github.com/TIS2017/SportovyKlub/files/1517432/rozdelenie.prace.docx)
Dievčatá tu je iba také predbežné rozdelenie práce na 4 celky. Neviem úplne presne povedať či to je rozdelené primerane ale tak skúste to zhodnotiť. Potom by sme si pohli povyberať ktorá chce ktorý a vytvorili by sme 4 issues každá na to svoje :)

**Comment by duricova72** [comment]
ja si môžem zobrať tú štvrtú časť - kmeňoví členovia

**Comment by lyvija** [comment]
Môžem trojku a teamviewer by som mohla v sobotu tak nejak podvečer - večer cca do 20:00. Vy jak môžete?

**Comment by gabikaSlani** [comment]
ja zase v sobotu vôbec lebo budem na ten 50-tke ale inak sa prisposobím kedykolvek

**Comment by lyvija** [comment]
Tak potom u mňa jedine v nedeľu poobede - neviem kedy obedujete, ale ja teda môžem o jednej byť na teamvieweri. Piatok nebudem doma a v nedeľu neskôr už tiež nie.

**Comment by gabikaSlani** [comment]
za mna môže byť

**Comment by dobsovicova** [comment]
Ak teda môžem Gabi, ja si vezmem tú jednotku a tebe ostane dvojka. A teamViewer mozem v nedelu od cca pol druhej.

**Comment by gabikaSlani** [comment]
Dobre tak ja mam dvojku.

**Comment by gabikaSlani** [comment]
Takže treba:
1. ešte raz spraviť poriadnu kontrolu, či je všetko okey v tej novej databáze, teda či ten skript funguje ako má
2. treba vymazať tie pomocné stĺpce
3. exportovať 2 spustiteľné súbory: jeden na vytvorenie databázy a jeden na naplnenie databázy
4. prepísať v kóde nový názov databázy a kedže sa nám pomenili názvy stĺpcov tabuliek a aj cudzie kluče, bude to treba v kóde pomeniť. A potom skontrolovať či všetko funguje ako má.
Toto všetko bude dobré spraviť kým každá začneme so svojou časťou implementácie.

5. Vymazať vetvy gabikaNavrh, testScenare
6. Každá si vytvorme issue a svoju vetvu na implementáciu.

**Comment by dobsovicova** [comment]
Tak ja vymazem vetvy a pozriem subor funkcie.php a zmenim vsetko podla novej databazy. :)

**Comment by gabikaSlani** [comment]
okey tak ja zmením podla novej databázy tie ostatné funkcie :)

**Comment by dobsovicova** [comment]
Na zaver treba spravit responzivny design. A ked budete pracovat na svojich castiach, tak skontrolujte aj funkcnost danej casti, ci funguju tlacitka, odkazy, vypisy atd. a ked nefunguje tak to skuste opravit prip. napiste a pozrieme sa na to.
