### ISSUE TITLE
prepis kodu po zmene databazy

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#24]
Vytvorila som novu vetvu prepisKodu. Nejake otazky/problemy na vas:

Subor **insert.php** vyzera to tak, ze tam sa vkladali len nejake testovacie udaje a ze ho nepotrebujeme skontroluj to a pripadne ho vymazeme. 

Podom dalsi subor **new_prihlas.php.** Netusim na co tento subor sluzi...to vyzera ako keby to bolo este z predchadzajucej verzie lebo ked tam vpisuje do databazy, tak vpisuje to do takych tabuliek, ktore nikde neboli v povodnej databze.

V subore **preteky.php j**e funkcia **prihlas_na_pretek()** tak sa vklada ta kategoria ale my sme zmenili kluc z nazvu na id a je to tam vselijak poprepletane s tym sa bude treba pohrat

V subore **preteky.php** je funkcia **vypis_zoznam_ostatne_table(**) je tam nejaky select a tiez nerozumiem naco je a ako ho mam zmenit...mozno na to prideme az po case ale davam do povedomia.

V subore **preteky.php** tam nam hadze aj errory v suvislosti s tabulkou **temp**. Tiez neviem na co je ale na nieco urcite sluzi. Neviem ako som to tam mala poprepisovat s tym sa tiez treba pohrat/.

**Comment by gabikaSlani** [comment]
V subore funkcie.php cela druha cast kodu vobec neni treba...to su zase len funkcie na vytvaranie tabuliek (oni vytvarali asi databazu z kodu) a vkladanie testovacich dat...tiez by sa to dalo vymazat

**Comment by dobsovicova** [comment]
insert.php vymazane.
new_prihlas.php vymazane.
preteky.php tam su problemy s kategoriou..vytvorene nove issue.
temp je ciastocne vyrieseny, tiez suvisi s kategoriami.
A vo funkce.php su nepotrebne veci vymazane.
