### ISSUE TITLE
vymazanie stlpca stare_id

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#27]
V SQLite sa síce nedá vymazat stlpec jednym prikazom ale da sa to vyriesit tak trochu inak...napad je tu:
https://stackoverflow.com/questions/5938048/delete-column-from-sqlite-table

Bolo by dobre to vyriesit lebo to robi problemy v prikazoch kde vytahujeme vsetko z tabuliek.

**Comment by lyvija** [comment]
Hotovo!
