### ISSUE TITLE
na serveri nefunguje ako ma

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#31]
No uz mi tu chybu ukázalo aj na localhoste. Bolo to presne vtedy ked nebol nikto prihlaseny na pretek a tym padom v tabulke prihlaseni pouzivatelia nezobrazovalo nikoho a teda sorter nemal koho zoradovat tak vyhodil tu chybu. Ale toto sa deje len pri tych pretekoch kde este nie je nikto prihlaseny. 
Naopak na serveri tu chybu vyhadzuje na kazdom jednom preteku aj ked na ten pretek v databaze su prihlaseni ludia. K databaze ma urcite pristup lebo odtial vypisuje tabulku pretekov. 

Fakt nechapem kde je chyba kedze je tam umiestnena aj uplne povodna verzia. 

Je to nalinkovene na gamaliz/source.
Na serveri su umiestnene 3 verzie: 
- source - to je povodna verzia co tam bola aj predtym plne funkcna,
- sourceGit - verzia ktora je vo vetve implementacia, davali sme ju tam spolu na stretnuti
- sourceNew - najnovsia verzia ktora je uz aj vo vetve master s novou databazou

**Comment by pavelpetrovic** [comment]
nemôže to byť v tom, že keď to ten sorter chce vyrenderovať, tak browser ešte nesparsoval html kód stránky? neviem, len taký jeden tip.

**Comment by gabikaSlani** [comment]
aha no dala som vytvorenie scriptu az na zaver kodu a error uz nevypisuje sice stale nevypisuje tabulku ale tak uz aspon nieco :) dakujeme

**Comment by gabikaSlani** [comment]
okey vyriesene. Problem bol s právami. Databáza potrebuje vsetky prava a aj ten subor nad nou. Dal sa z nej robit len Select inak sa tam nic nevytvaralo ani nevkladalo.

**Comment by gabikaSlani** [comment]
Takže vždy ked budeme testovat na serveri databáza musí mat práva 0777 aj priecinok sorter.
