### ISSUE TITLE
diakritika

### ISSUE THREAD

**Issue by gabikaSlani** [TIS2017/SportovyKlub#38]
Diakritiku sa mi asi podarilo opravit ale potom keby ste si nahodou vsimli ze niekde inde nefunguje dajte vediet.

**Comment by lyvija** [comment]
Chyba bude v niečom inom, lebo stále to nebere ľ, č, ť, ž, ň. So š je spokojný :D

**Comment by gabikaSlani** [comment]
ale ty nemas este moju verziu...tu som este nepushla

**Comment by lyvija** [comment]
tak potom sa veľmi teším. dnes mám problém s časovou následnosťou (hodiny dni udalosti)

**Comment by gabikaSlani** [comment]
v pohode :)

**Comment by gabikaSlani** [comment]
ok no v tejto najnovsej verzii sa zmazala ta moja oprava diakritiky ale uz som to opravila

**Comment by pavelpetrovic** [comment]
cele to prosim vas skontroluje, ci tam mate tie zmeny, ktore ste robili.
tym, ze ste nezachovali standardny postup pri gitovani Vam tam povznikali
nekonzistetne repozitare, ktore mohli nieco nove pomazat.

vzdy ked urobite "git add" na nieco, tak to potom treba hned aj commitnut
do svojej vlastnej branch a idealne aj co najskor pushnut a potom cez pull request
mergenut. ak urobite pull request z webu, ale nemate to pushnute, 
tak to nedopadne dobre...

p.
