### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by dobsovicova** [TIS2017/SportovyKlub#46]
v kategorie_new.php ked zadam nazov novej kategorie a potvrdim, tak neviem presmerovat stranku na adresu kategorie.php

**Comment by dobsovicova** [comment]
to iste aj presmerovanie oddiely_new.php -> oddiely.php

**Comment by gabikaSlani** [comment]
skus nieco taketo   echo '<META HTTP-EQUIV="refresh" CONTENT="0;URL=kategorie.php">';

**Comment by gabikaSlani** [comment]
META HTTP-EQUIV="refresh" CONTENT="0;URL=index.php">;

**Comment by gabikaSlani** [comment]
skus nieco taketo <META HTTP-EQUIV="refresh" CONTENT="0;URL=kategorie.php">;

**Comment by gabikaSlani** [comment]
skus nieco taketo META HTTP-EQUIV="refresh" CONTENT="0;URL=kategorie.php">;

**Comment by dobsovicova** [comment]
vdaka. mala som zle uvodzovky
