### ISSUE TITLE
uprava hlavicka - presmerovanie na archiv.php

### ISSUE THREAD

**Issue by lyvija** [TIS2017/SportovyKlub#53]
Momentálne sa nedá cez navigáciu dostať do archívu, zrejme to z mojej verzie vymazalo. Treba to vo funkcie.php upraviť vo funkcii hlavicka.

**Comment by dobsovicova** [comment]
aj toto si pridavam ku svojim urobenym zmenam a teda aj toto je vyriesene. :)
