### ISSUE TITLE
nespravne presmerovanie na kategorie.php po vytvoreni noveho oddielu

### ISSUE THREAD

**Issue by lyvija** [TIS2017/SportovyKlub#57]
Keď potvrdím vytvorenie nového oddielu, presmeruje ma to na kategorie.php. Len na 25. riadku treba zmeniť kategorie.php na oddiely.php.

**Comment by dobsovicova** [comment]
vdaka, uz som to opravila. S dalsimi zmenami co spravim to hodim do mastra :)
