### ISSUE TITLE
zoznam neprihlasenych na pretek - uprav

### ISSUE THREAD

**Issue by dobsovicova** [TIS2017/SportovyKlub#61]
Cloveku, ktory nie je admin, dava vo vypise neprihlasenych pouz. na pretek pri menach moznost uprav. To by asi nemalo, ci?

**Comment by gabikaSlani** [comment]
Vies co to sa ja nemenila to tak bolo a tym ze oni nemaju pouzivatelske rozhranie tak aby si mali ako zmenit profil. Ci nie? Nebolo v poziadavkach aby sme to nechali len pri adminovi

**Comment by pavelpetrovic** [comment]
ak su nejake nejasnosti, tak nevahajte napisat otazku zadavatelovi

**Comment by lyvija** [comment]
Má to tak byť, keďže neexistuje prihlasovanie používateľov. My tým pádom nevieme pre niekoho povoliť a pre niekoho úpravu zakázať - buď povolíme každému, ako je to teraz, alebo nikomu - takže používateľ nebude môcť ani sám sebe upraviť profil.
